App_Evaluaciones/Controllers/EvaluacionController.cs
using App_Evaluaciones.Models;
using App_Evaluaciones.Models.Dto;
using App_Evaluaciones.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace App_Evaluaciones.Controllers
{
    public class EvaluacionController : Controller
    {
        private readonly IEvaluacionRepository _evaluacionRepository;
        private readonly IUserRepository _userRepository;
        public EvaluacionController(IEvaluacionRepository evaluacionRepository,IUserRepository userRepository)
        {
            _evaluacionRepository = evaluacionRepository;
            _userRepository = userRepository;
        }
        public async Task<IActionResult> Index(int IdEva, int IdUser)
        {
            var usuario = await _userRepository.Get_UserXIduser(IdUser);
            var preguntas = await _evaluacionRepository.GetAll_Preguntas(IdEva);
            EvaluacionView evaluacionView = new EvaluacionView();
            Evaluado evaluado = new();
            List<Pregunta> pregunta = new();
            evaluacionView.Evaluado = evaluado;
            evaluacionView.Preguntas = pregunta;
            evaluacionView.Evaluado.Cedula = usuario.Cedula;
            evaluacionView.Evaluado.Parque = usuario.Parque;
            evaluacionView.Evaluado.Proceso = usuario.Proceso;
            evaluacionView.Evaluado.Cargo = usuario.Cargo;
            evaluacionView.Evaluado.Nombre = usuario.Nombre;
            evaluacionView.Preguntas = preguntas;
            return View(evaluacionView);
        }

        public IActionResult ViewEvalucion(int IdEva)
        {
            var preguntas = _evaluacionRepository.GetAll_Preguntas(IdEva);
            return View();
        }
       
        public async Task<IActionResult> CrearEvaluacion()
        {
            // Si el modelo no es válido, devolver la vista con los datos actuales
            return View();
        }
        [HttpPost]
        public IActionResult CrearEvaluacion(EvaluacionCreateDto model)
        {
            if (ModelState.IsValid)
            {
                // Guardar en base de datos
                // ...
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

App_Evaluaciones/Controllers/HomeController.cs
using App_Evaluaciones.Models;
using App_Evaluaciones.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace App_Evaluaciones.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserRepository _userRespository;
        private readonly IEvaluacionRepository _evalacionRespository;

        public HomeController(ILogger<HomeController> logger, IUserRepository userRespository, IEvaluacionRepository evalacionRespository)
        {
            _logger = logger;
            _userRespository = userRespository;
            _evalacionRespository = evalacionRespository;
        }

        public async Task<IActionResult> Index()
        {
            //_userRespository.GetAll_User();
            var evaluaciones = await _evalacionRespository.GetAll_Evaluacion();
            //var evaluados = await _userRespository.Get_Evaluado("1124862267",3);
            //Extraemos la Cedula registrada en los Claims cuando se logio
            string? cedula = User.FindFirst("Cedula")?.Value;
            if (evaluaciones.Any())
            {
                foreach (var item in evaluaciones)
                {
                    //Extraemos los usuarios a evaluar por cada evaluacion que tengamos asignadas
                    item.Evaluados = await _userRespository.Get_Evaluado(cedula, item.EvaluacionId);
                }
            }
            if (cedula != null)
            {
                Usuario usuario = await _userRespository.Get_User(cedula);
                usuario.Evalaciones = evaluaciones;
                return View(usuario);
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App_Evaluaciones/Views/Home/Index.cshtml
@model Usuario
@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    <div class="col-10 offset-1 col-sm-6 offset-sm-6 mx-auto" >
        <div class="card mb-3" style="max-width: 640px;">
            <div class="row g-0">
                <div class="col-md-4 text-center align-content-center">
                    <img src="~/Img/user.png" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body ">
                        <h5 class="card-title">@Model.Nombre</h5>
                        <p class="card-text mb-1"><strong>Cedula: </strong>@Model.Cedula </p>
                         <p class="card-text  mb-1"><strong>Parque: </strong>@Model.Parque </p>
                          <p class="card-text  mb-1"><strong>Cargo: </strong>@Model.Cargo </p>
                           <p class="card-text  mb-1"><strong>Grupo: </strong>@Model.Grupo </p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<a type="button" class="btn btn-outline-dark" asp-controller="Evaluacion" asp-action="CrearEvaluacion">Crear</a>
@foreach (var Eva in @Model.Evalaciones)
{

    <div class="card cardmy">
        <div class="card-body">
            <p class="text-end">Fecha Limite: <i class="bi bi-calendar-week-fill">  @Eva.FCierre</i></p>
            <h5 class="card-title">@Eva.Nombre</h5>
            <p class="card-text ">@Eva.Descripcion</p>
            <div class="d-flex gap-4 align-items-center">
                <h6>Total <span class="badge text-bg-dark bg-dark">@Eva.Evaluados.Count()</span></h6>
                <h6>Pendientes <span class="badge text-bg-danger bg-danger">New</span></h6>
            </div>
            <br>
            <a class="btn btn-outline-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                Ver Detalle
            </a>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Cargo</th>
                                <th scope="col">Grupo</th>
                                <th scope="col">Handle</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var Evaluado in Eva.Evaluados)
                            {
                                <tr>                                    
                                    <td>@Evaluado.Nombre</td>
                                    <td>@Evaluado.Cargo</td>
                                    <td>@Evaluado.Grupo</td>
                                    <td><a type="button" class="btn btn-outline-dark" asp-action="Index" asp-controller="Evaluacion" asp-route-IdEva="@Eva.EvaluacionId" asp-route-IdUser="@Evaluado.UserId">Abrir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
   
}